# Gemini API Configuration
# Get your API key from Google AI Studio: https://aistudio.google.com/
# gemini_api_key: "AIzaSyCuyn0PU-ZXvYI9T4U_PRgkLaPopd32fn8"
gemini_api_key: "AIzaSyD4JmIpmwh7Mh_jRLdhN6C6eGiz2LNr_oA"
# gemini_api_key: "AIzaSyDZBCU31q3wmVsUdLJ5qtzKivL8kF97G28"

# General Settings
novel_file_name: "infinite_fears.md"
character_profiles_directory: "output/characters"
story_arc_file: "output/story_arc.json"
rewrite_cycles: 3

# Git Settings
# Set to false to disable automatic git push, useful for local development.
# Only commits will be made locally.
git_push_enabled: false